In [ ]:
import numpy as np
from collections import defaultdict, deque

In [3]:
state_memory = np.load('data/state_memory_25000_f1.npy')
edge_memory = np.load('data/edge_memory_25000_f1.npy')

FileNotFoundError: [Errno 2] No such file or directory: 'data/state_memory.npy'

In [125]:
len(state_memory)
len(edge_memory)

6014

In [126]:
node_memory = deque(maxlen=len(state_memory))
tree_memory = defaultdict(lambda: 0)

# make tree
for v in state_memory:
    v_t = tuple(v)
    node_memory.append(v_t)
tmp = list(zip(node_memory, edge_memory))
for v in tmp:
    tree_memory[v[0]] += v[1]

In [127]:
len(tree_memory)

2854

In [128]:
root = tuple(np.zeros((3, 3, 3), 'float').flatten())

In [129]:
print(np.around(tree_memory[root], decimals=1))

[[[ 107.    39.     0.    88.6]
  [  74.    21.     0.    89.5]
  [ 116.    44.     0.    88.8]]

 [[  50.     7.     0.    88.6]
  [ 208.    98.     0.    89.5]
  [  43.     3.     0.    88.6]]

 [[ 103.    39.     0.    88.9]
  [  26.    -6.     0.    88.3]
  [  73.    21.     0.    89.3]]]


In [12]:
# make policy
n_val = deque(maxlen=9)
pi_val = deque(maxlen=9)
e_x = deque(maxlen=9)
state_data = deque(maxlen=len(tree_memory))
pi_data = deque(maxlen=len(tree_memory))


for k, v in tree_memory.items():
    state_data.append(k)
    for r in range(3):
        for c in range(3):
            n_val.append(v[r][c][0])
    for i in range(9):
        e_x.append(np.exp(n_val[i] - np.max(n_val)))
    for i in range(9):
        pi_val.append(e_x[i] / np.sum(e_x, axis=0))       
    pi_data.append(np.asarray(pi_val).reshape((3, 3)))

def softmax(state):    
    if tuple(state.flatten()) in state_data:
        i = tuple(state.flatten())
        j = state_data.index(i)
        board = np.asarray(state_data[j]).reshape((3, 3, 3))
        print(board[0] + board[1] * 2, '\n')
        print((pi_data[j].round(decimals=4)))
    else:
        return 0

In [13]:
bug = np.zeros((3, 3, 3), 'float')
bug[0][0][0] = 1
bug[0][0][1]
bug[0][0][2] = 1
bug[0][1][0]
bug[0][1][1]
bug[0][1][2] = 1
bug[0][2][0]
bug[0][2][1] = 1
bug[0][2][2]
bug[1][0][0]
bug[1][0][1] = 1
bug[1][0][2]
bug[1][1][0] = 1
bug[1][1][1] = 1
bug[1][1][2]
bug[1][2][0]
bug[1][2][1]
bug[1][2][2]
bug[2][0][0]
bug[2][0][1] = 1
bug[2][0][2]
bug[2][1][0] = 1
bug[2][1][1] = 1
bug[2][1][2]
bug[2][2][0]
bug[2][2][1]
bug[2][2][2]
bug

array([[[ 1.,  0.,  1.],
        [ 0.,  0.,  1.],
        [ 0.,  1.,  0.]],

       [[ 0.,  1.,  0.],
        [ 1.,  1.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  1.,  0.],
        [ 1.,  1.,  0.],
        [ 0.,  0.,  0.]]])

In [14]:
zero = np.zeros((3, 3, 3), 'float')

In [15]:
softmax(zero)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]] 

[[ 0.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  0.]]


In [16]:
tree_memory[tuple(bug.flatten())]

0

In [81]:
val = [3, 3, 3, 4]
np.random.choice(len(val))

3

In [97]:
for _ in range(10):
    print(np.random.choice(2, replace=False))

0
0
1
1
0
0
0
0
0
0
