In [45]:
import numpy as np
np.set_printoptions(suppress=True)
from collections import defaultdict, deque
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [56]:
state_memory = np.load('data/state_memory_e800_c5a0.85.npy')
edge_memory = np.load('data/edge_memory_e800_c5a0.85.npy')

node_memory = deque(maxlen=len(state_memory))
tree_memory = defaultdict(lambda: 0)

# make tree
for v in state_memory:
    v_t = tuple(v)
    node_memory.append(v_t)
tmp = list(zip(node_memory, edge_memory))
for v in tmp:
    tree_memory[v[0]] += v[1]

In [57]:
len(state_memory)
len(edge_memory)

6053

6053

In [58]:
len(tree_memory)

3451

In [59]:
round(len(tree_memory)/len(state_memory), 2)

0.57

In [60]:
root = tuple(np.zeros((9, 3, 3), 'float').flatten())

In [66]:
print(np.around(tree_memory[root], decimals=0))

[[[ 107.   33.    0.   89.]
  [  73.   15.    0.   88.]
  [ 114.   37.    0.   89.]]

 [[  44.   -2.    0.   90.]
  [ 221.   97.    0.   89.]
  [  69.   13.    0.   89.]]

 [[  48.    3.    0.   89.]
  [  56.    6.    0.   88.]
  [  68.   11.    0.   88.]]]


In [67]:
first = np.zeros((9, 3, 3), 'float')
first[4][1][1] = 1
first[8][1][1] = 1
first = tuple(first.flatten())

In [68]:
print(np.around(tree_memory[first], decimals=0))

[[[  7.  -6.   0.  12.]
  [  7.  -6.   0.  12.]
  [ 23.  -6.   0.  12.]]

 [[ 12.  -6.   0.  12.]
  [  0.   0.   0.   0.]
  [ 10.  -6.   0.  12.]]

 [[ 19.  -6.   0.  12.]
  [ 10.  -6.   0.  12.]
  [ 11.  -6.   0.  12.]]]


In [69]:
second = np.zeros((9, 3, 3), 'float')
second[0][1][1] = 1
second[8][1][1] = 1
second = tuple(second.flatten())

In [70]:
print(np.around(tree_memory[second], decimals=0))

[[[ 15.  -3.   0.  15.]
  [ 10.  -6.   0.  15.]
  [ 17.  -7.   0.  15.]]

 [[  7.  -6.   0.  15.]
  [  0.   0.   0.   0.]
  [ 10.  -6.   0.  15.]]

 [[ 25.  -7.   0.  15.]
  [ 18.  -7.   0.  15.]
  [ 20.  -7.   0.  15.]]]
