In [2]:
import numpy as np
np.set_printoptions(suppress=True)
from collections import defaultdict, deque
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [13]:
state_memory = np.load('data/state_memory_3kz.npy')
edge_memory = np.load('data/edge_memory_3kz.npy')

node_memory = deque(maxlen=len(state_memory))
tree_memory = defaultdict(lambda: 0)

# make tree
for v in state_memory:
    v_t = tuple(v)
    node_memory.append(v_t)
tmp = list(zip(node_memory, edge_memory))
for v in tmp:
    tree_memory[v[0]] += v[1]

In [14]:
len(state_memory)
len(edge_memory)

22560

22560

In [15]:
len(tree_memory)

11091

In [16]:
round(len(tree_memory)/len(state_memory), 2)

0.49

In [17]:
root = tuple(np.zeros((9, 3, 3), 'float').flatten())

In [18]:
print(np.around(tree_memory[root], decimals=0))

[[[ 343.  117.    0.  334.]
  [ 218.   54.    0.  332.]
  [ 266.   76.    0.  333.]]

 [[ 151.   15.    0.  333.]
  [ 945.  414.    0.  332.]
  [ 173.   25.    0.  333.]]

 [[ 330.  117.    0.  334.]
  [ 233.   57.    0.  332.]
  [ 341.  105.    0.  337.]]]


In [19]:
first = np.zeros((9, 3, 3), 'float')
first[4][1][1] = 1
first[8][1][1] = 1
first = tuple(first.flatten())

In [20]:
print(np.around(tree_memory[first], decimals=0))

[[[ 85. -22.   0.  58.]
  [ 39. -25.   0.  59.]
  [ 89. -24.   0.  58.]]

 [[ 58. -21.   0.  59.]
  [  0.   0.   0.   0.]
  [ 42. -22.   0.  58.]]

 [[ 41. -23.   0.  58.]
  [ 52. -28.   0.  60.]
  [ 62. -21.   0.  58.]]]


In [21]:
second = np.zeros((9, 3, 3), 'float')
second[0][1][1] = 1
second[8][1][1] = 1
second = tuple(second.flatten())

In [22]:
print(np.around(tree_memory[second], decimals=0))

[[[ 63. -26.   0.  60.]
  [ 39. -28.   0.  60.]
  [ 67. -29.   0.  59.]]

 [[ 46. -24.   0.  60.]
  [  0.   0.   0.   0.]
  [ 60. -29.   0.  60.]]

 [[ 70. -29.   0.  60.]
  [ 40. -29.   0.  60.]
  [ 92. -34.   0.  59.]]]
