In [1]:
import numpy as np
from collections import defaultdict, deque
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
state_memory = np.load('data/state_memory_25k.npy')
edge_memory = np.load('data/edge_memory_25k.npy')

node_memory = deque(maxlen=len(state_memory))
tree_memory = defaultdict(lambda: 0)

# make tree
for v in state_memory:
    v_t = tuple(v)
    node_memory.append(v_t)
tmp = list(zip(node_memory, edge_memory))
for v in tmp:
    tree_memory[v[0]] += v[1]

In [8]:
len(state_memory)
len(edge_memory)/32

208073

6502.28125

In [4]:
len(tree_memory)

20925

In [5]:
round(len(tree_memory)/len(state_memory), 2)

0.1

In [6]:
root = tuple(np.zeros((9, 3, 3), 'float').flatten())

In [8]:
print(np.around(tree_memory[root], decimals=1))

[[[ 1391.    155.      0.   2774.2]
  [ 1931.    228.      0.   2782.4]
  [ 1005.    103.      0.   2776.8]]

 [[ 3985.    496.      0.   2779.6]
  [ 9073.   1164.      0.   2777.6]
  [ 3534.    436.      0.   2779.9]]

 [[ 1266.    139.      0.   2770.4]
  [ 1298.    141.      0.   2779.7]
  [ 1517.    169.      0.   2779.4]]]
