In [48]:
import numpy as np
from collections import defaultdict, deque
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [49]:
state_memory = np.load('data/state_memory_he.npy')
edge_memory = np.load('data/edge_memory_he.npy')

node_memory = deque(maxlen=len(state_memory))
tree_memory = defaultdict(lambda: 0)

# make tree
for v in state_memory:
    v_t = tuple(v)
    node_memory.append(v_t)
tmp = list(zip(node_memory, edge_memory))
for v in tmp:
    tree_memory[v[0]] += v[1]

In [50]:
len(state_memory)
len(edge_memory)

70161

70161

In [51]:
len(tree_memory)

12398

In [52]:
round(len(tree_memory)/len(state_memory), 2)

0.18

In [53]:
root = tuple(np.zeros((9, 3, 3), 'float').flatten())

In [54]:
print(np.around(tree_memory[root], decimals=-1))

[[[ 2720.   730.     0.  1000.]
  [   90.    10.     0.  1000.]
  [  410.   100.     0.  1000.]]

 [[  600.   150.     0.  1000.]
  [ 2020.   540.     0.  1000.]
  [  160.    30.     0.  1000.]]

 [[ 2700.   730.     0.  1000.]
  [  160.    30.     0.  1000.]
  [  150.    20.     0.  1000.]]]
